### ISSUE TITLE
PlausibilityTestSuite test JumpAzimuthChangeFilter failing

### ISSUE THREAD

**Issue by chrisbc** [opensha/opensha-ucerf3#19]
We have a failing test 

```
org.opensha.sha.earthquake.faultSysSolution.ruptures.plausibility.impl.PlausibilityTestSuite > org.opensha.sha.earthquake.faultSysSolution.ruptures.plausibility.impl.JumpAzimuthChangeFilterTests.testJump FAILED
    java.lang.IllegalStateException
        at com.google.common.base.Preconditions.checkState(Preconditions.java:491)
        at org.opensha.sha.earthquake.faultSysSolution.ruptures.plausibility.impl.JumpAzimuthChangeFilter.calc(JumpAzimuthChangeFilter.java:168)
        at org.opensha.sha.earthquake.faultSysSolution.ruptures.plausibility.impl.JumpAzimuthChangeFilter.testJump(JumpAzimuthChangeFilter.java:97)
        at org.opensha.sha.earthquake.faultSysSolution.ruptures.plausibility.impl.JumpAzimuthChangeFilterTests.jump(JumpAzimuthChangeFilterTests.java:15)
        at org.opensha.sha.earthquake.faultSysSolution.ruptures.plausibility.impl.JumpAzimuthChangeFilterTests.testJump(JumpAzimuthChangeFilterTests.java:20)
```

**Comment by chrisbc** [comment]
@kevinmilner this is fixed in https://github.com/opensha/opensha-ucerf3/pull/20
